from .base import *

DEBUG = DEBUG_SECRET['DEBUG']

ALLOWED_HOSTS = DEBUG_SECRET['ALLOWED_HOSTS']

WSGI_APPLICATION = 'django_site.wsgi.debug.application'

CELERY_BROKER_URL = 'redis://%s:6379/0' % DEBUG_SECRET['CELERY_BROKER_URL']
CELERY_RESULT_BACKEND = 'redis://%s:6379/0' % DEBUG_SECRET['CELERY_RESULT_BACKEND']
